name: Release
on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip system
        run: zip -r aurore.zip . -x '.git/*' '.github/*'
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: aurore.zip
